# Generated by Django 3.2.6 on 2022-10-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=30)),
                ('city', models.CharField(blank=True, default='0.0.0.0', max_length=15, null=True)),
                ('lat_lng', models.CharField(blank=True, default='0.0.0.0', max_length=30, null=True)),
            ],
        ),
    ]
