# Generated by Django 3.2.6 on 2022-09-24 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile', models.CharField(max_length=13)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 24, 14, 54, 44, 606882))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 9, 24, 14, 54, 44, 606882))),
                ('isVerified', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
