# Generated by Django 3.2.6 on 2022-09-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='Mobile',
            field=models.CharField(max_length=13),
        ),
    ]
