# Generated by Django 3.2.6 on 2022-09-24 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_alter_phonemodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 24, 15, 34, 27, 639266)),
        ),
    ]
