# Generated by Django 3.2.6 on 2022-09-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_auto_20220925_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='counter',
        ),
    ]
