# Generated by Django 3.2.6 on 2022-09-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_phonemodel_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='phonemodel',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='phonemodel',
            name='lat_lng',
        ),
    ]
