# Generated by Django 3.2.6 on 2022-09-24 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_alter_phonemodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 24, 10, 17, 52, 532787, tzinfo=utc)),
        ),
    ]
