# Generated by Django 3.2.6 on 2022-09-24 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_alter_phonemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=30),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 24, 11, 44, 32, 279352, tzinfo=utc)),
        ),
    ]
