# Generated by Django 3.2.6 on 2022-09-24 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0007_auto_20220924_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='city',
            field=models.CharField(default='NaN', max_length=15),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='lat',
            field=models.CharField(default='NaN', max_length=4),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='long',
            field=models.CharField(default='NaN', max_length=4),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 24, 12, 20, 59, 859621, tzinfo=utc)),
        ),
    ]
