# Generated by Django 3.2.6 on 2022-10-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0007_auto_20220930_1612'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonemodel',
            unique_together=set(),
        ),
    ]
