# Generated by Django 3.2.6 on 2022-09-25 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_responsemodel_form_id'),
        ('verification', '0012_alter_phonemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='form',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='feedback.responsemodel'),
        ),
    ]
