# Generated by Django 3.2.6 on 2022-09-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0014_alter_phonemodel_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='form',
        ),
    ]
