# Generated by Django 3.2.6 on 2022-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0015_remove_phonemodel_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='city',
            field=models.CharField(blank=True, default='NaN', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='lat_lng',
            field=models.CharField(blank=True, default='NaN', max_length=30, null=True),
        ),
    ]
