# Generated by Django 3.2.6 on 2022-10-03 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='responseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('res1', models.CharField(max_length=50)),
                ('res2', models.CharField(max_length=50)),
                ('res3', models.CharField(max_length=300)),
                ('res4', models.CharField(max_length=1)),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.phonemodel')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.stationmodel')),
            ],
        ),
    ]
