# Generated by Django 3.2.6 on 2022-09-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verification', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='responseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('res1', models.CharField(max_length=1)),
                ('res2', models.CharField(max_length=1)),
                ('res3', models.CharField(max_length=200)),
                ('res4', models.CharField(max_length=1)),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.phonemodel')),
            ],
        ),
    ]
