# Generated by Django 3.2.6 on 2022-09-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsemodel',
            name='res4',
            field=models.CharField(default='2', max_length=1),
        ),
    ]
