# Generated by Django 3.2.6 on 2022-09-25 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsemodel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
