# Generated by Django 3.2.6 on 2022-09-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20220925_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
