# Generated by Django 3.2.6 on 2022-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_responsemodel_res4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='res4',
            field=models.CharField(max_length=1),
        ),
    ]
