# Generated by Django 3.2.6 on 2022-09-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20220925_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='res3',
            field=models.CharField(max_length=300),
        ),
    ]
