# Generated by Django 3.2.6 on 2022-09-25 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0013_phonemodel_form'),
        ('feedback', '0004_responsemodel_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.phonemodel'),
        ),
    ]
