# Generated by Django 3.2.6 on 2022-09-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20220927_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='res3',
            field=models.CharField(max_length=200),
        ),
    ]
