# Generated by Django 3.2.6 on 2022-09-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_responsemodel_form_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsemodel',
            old_name='form_id',
            new_name='res_id',
        ),
    ]
