# Generated by Django 3.2.6 on 2022-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20220929_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='res1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='res2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='res3',
            field=models.CharField(max_length=300),
        ),
    ]
