# Generated by Django 3.2.6 on 2022-09-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20220930_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='city',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='ip_address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='lat_lng',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
