# Generated by Django 3.2.6 on 2022-09-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_auto_20220930_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsemodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='responsemodel',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='responsemodel',
            name='lat_lng',
        ),
    ]
