# Generated by Django 3.2.6 on 2022-09-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
