# Generated by Django 3.2.6 on 2022-09-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_adminmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmodel',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='name',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
