# Generated by Django 3.2.6 on 2022-10-03 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='stationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=10)),
                ('station_name', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=15)),
                ('subdivision', models.CharField(max_length=10)),
                ('address', models.CharField(default=' ', max_length=100)),
                ('contact', models.CharField(max_length=12)),
                ('pincode', models.CharField(max_length=6)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
