# Generated by Django 3.2.6 on 2022-10-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=10)),
                ('station_name', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=15)),
                ('subdivision', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
