# Generated by Django 3.2.6 on 2022-10-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmodel',
            name='email',
            field=models.CharField(max_length=20),
        ),
    ]
