# Generated by Django 3.2.6 on 2022-10-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_stationmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmodel',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
