# Generated by Django 3.2.6 on 2022-10-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_auto_20221006_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlroomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=26)),
            ],
        ),
    ]
