# Generated by Django 3.2.6 on 2022-10-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_controlroommodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlroommodel',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
