# Generated by Django 3.2.6 on 2022-10-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_alter_controlroommodel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlroommodel',
            name='district_id',
            field=models.CharField(default='', max_length=4),
        ),
    ]
